"""Initial migration

Revision ID: initial
Revises: 
Create Date: 2026-01-28 06:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_source', sa.String(length=16), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=True),
    sa.Column('ktru_code', sa.String(length=64), nullable=False),
    sa.Column('okpd2_code', sa.String(length=64), nullable=True),
    sa.Column('manufacturer_target', sa.String(length=256), nullable=True),
    sa.Column('customer_region', sa.String(length=64), nullable=False),
    sa.Column('law', sa.String(length=16), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('execution_statuses', postgresql.ARRAY(sa.String(length=8)), nullable=False),
    sa.Column('limit_contracts', sa.Integer(), nullable=False),
    sa.Column('found_total', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('nmc_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('selected_contract_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('target_specs', postgresql.JSONB(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_request_celery_task_id', 'search_request', ['celery_task_id'], unique=False)
    op.create_index('ix_search_request_ktru_code', 'search_request', ['ktru_code'], unique=False)
    op.create_index('ix_search_request_status', 'search_request', ['status'], unique=False)
    
    op.create_table('contract_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('reestr_number', sa.String(length=64), nullable=False),
    sa.Column('contract_url', sa.Text(), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.Column('manufacturer_found', sa.String(length=256), nullable=True),
    sa.Column('manufacturer_match', sa.Boolean(), nullable=True),
    sa.Column('is_2025_plus', sa.Boolean(), nullable=False),
    sa.Column('accepted_for_nmc', sa.Boolean(), nullable=False),
    sa.Column('specs_raw', sa.Text(), nullable=True),
    sa.Column('raw_data_json', postgresql.JSONB(), nullable=False),
    sa.Column('ai_analysis', postgresql.JSONB(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'reestr_number', name='uq_search_contract'),
    sa.ForeignKeyConstraint(['search_id'], ['search_request.id'], ondelete='CASCADE')
    )
    op.create_index('ix_contract_result_ai_score', 'contract_result', ['ai_score'], unique=False)
    op.create_index('ix_contract_result_match_type', 'contract_result', ['match_type'], unique=False)
    op.create_index('ix_contract_result_reestr_number', 'contract_result', ['reestr_number'], unique=False)
    op.create_index('ix_contract_result_search_id', 'contract_result', ['search_id'], unique=False)
    
    op.create_table('spec_comparison_row',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_result_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('match_status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_result.id'], ondelete='CASCADE')
    )
    op.create_index('ix_spec_comparison_row_contract_result_id', 'spec_comparison_row', ['contract_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spec_comparison_row_contract_result_id', table_name='spec_comparison_row')
    op.drop_table('spec_comparison_row')
    op.drop_index('ix_contract_result_search_id', table_name='contract_result')
    op.drop_index('ix_contract_result_reestr_number', table_name='contract_result')
    op.drop_index('ix_contract_result_match_type', table_name='contract_result')
    op.drop_index('ix_contract_result_ai_score', table_name='contract_result')
    op.drop_table('contract_result')
    op.drop_index('ix_search_request_status', table_name='search_request')
    op.drop_index('ix_search_request_ktru_code', table_name='search_request')
    op.drop_index('ix_search_request_celery_task_id', table_name='search_request')
    op.drop_table('search_request')
    # ### end Alembic commands ###