"""init

Revision ID: 2783bac2be90
Revises: 
Create Date: 2026-02-06 09:56:52.559127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2783bac2be90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_requests',
    sa.Column('input_source', sa.String(length=255), nullable=False),
    sa.Column('ktru_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='searchstatus'), nullable=False),
    sa.Column('limit_contracts', sa.Integer(), nullable=False),
    sa.Column('selected_contract_ids', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('nmc_value', sa.Float(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('region_filter', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('total_contracts_found', sa.Integer(), nullable=False),
    sa.Column('contracts_processed', sa.Integer(), nullable=False),
    sa.Column('processing_started_at', sa.String(length=20), nullable=True),
    sa.Column('processing_completed_at', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_results',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('reestr_number', sa.String(length=100), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.String(length=20), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'PARTIAL', 'SIMILAR', 'NO_MATCH', name='matchtype'), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_inn', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_inn', sa.String(length=20), nullable=True),
    sa.Column('contract_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.String(length=20), nullable=True),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_results_reestr_number'), 'contract_results', ['reestr_number'], unique=False)
    op.create_index(op.f('ix_contract_results_search_id'), 'contract_results', ['search_id'], unique=False)
    op.create_table('spec_comparison_rows',
    sa.Column('contract_result_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCH', 'MISMATCH', 'PARTIAL', 'UNKNOWN', name='matchstatus'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('comparison_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_comparison_rows_contract_result_id'), 'spec_comparison_rows', ['contract_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spec_comparison_rows_contract_result_id'), table_name='spec_comparison_rows')
    op.drop_table('spec_comparison_rows')
    op.drop_index(op.f('ix_contract_results_search_id'), table_name='contract_results')
    op.drop_index(op.f('ix_contract_results_reestr_number'), table_name='contract_results')
    op.drop_table('contract_results')
    op.drop_table('search_requests')
    # ### end Alembic commands ###
