"""init

Revision ID: 9ef761e20156
Revises: 
Create Date: 2026-02-06 10:38:48.077306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ef761e20156'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_source', sa.String(length=255), nullable=False),
    sa.Column('ktru_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='searchstatus'), nullable=False),
    sa.Column('limit_contracts', sa.Integer(), nullable=True),
    sa.Column('selected_contract_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('nmc_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('search_parameters', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('reestr_number', sa.String(length=100), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'PARTIAL', 'FUZZY', 'NO_MATCH', name='matchtype'), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('contract_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('contract_price', sa.Float(), nullable=True),
    sa.Column('contract_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_comparison_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_result_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCH', 'PARTIAL_MATCH', 'NO_MATCH', 'NOT_APPLICABLE', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('comparison_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_comparison_rows')
    op.drop_table('contract_results')
    op.drop_table('search_requests')
    # ### end Alembic commands ###
