"""Initial migration: create search_requests, contract_results, spec_comparison_rows tables

Revision ID: c0bfadab1819
Revises: 
Create Date: 2026-02-09 17:41:17.066045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c0bfadab1819'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'DONE', 'STOPPED', 'ERROR', name='search_status'), nullable=False),
    sa.Column('object_name', sa.String(length=500), nullable=True),
    sa.Column('ktru', sa.String(length=100), nullable=True),
    sa.Column('okpd2', sa.String(length=100), nullable=True),
    sa.Column('okved2', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('nmc_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_requests_status'), 'search_requests', ['status'], unique=False)
    op.create_table('contract_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('reestr_number', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'PARTIAL', 'SIMILAR', 'NO_MATCH', name='match_type'), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_data_json', sa.JSON(), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_results_reestr_number'), 'contract_results', ['reestr_number'], unique=False)
    op.create_index(op.f('ix_contract_results_search_id'), 'contract_results', ['search_id'], unique=False)
    op.create_table('spec_comparison_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_result_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCH', 'PARTIAL_MATCH', 'NO_MATCH', 'NOT_SPECIFIED', name='match_status'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('importance_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_comparison_rows_contract_result_id'), 'spec_comparison_rows', ['contract_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spec_comparison_rows_contract_result_id'), table_name='spec_comparison_rows')
    op.drop_table('spec_comparison_rows')
    op.drop_index(op.f('ix_contract_results_search_id'), table_name='contract_results')
    op.drop_index(op.f('ix_contract_results_reestr_number'), table_name='contract_results')
    op.drop_table('contract_results')
    op.drop_index(op.f('ix_search_requests_status'), table_name='search_requests')
    op.drop_table('search_requests')
    # ### end Alembic commands ###
